### ISSUE TITLE
sqlite doesn't builds

### ISSUE THREAD

**Issue by bbigras** [tnantoka/connect-sqlite#1]
The sqlite module doesn't builds.

Maybe you could ship : https://github.com/rbochenski/node-sqlite

**Comment by madhacked** [comment]
I forked the main code to work with the sqlite3 library.  I could not get sqlite to compile.  With the different backend, I was able to get this up and running.  I know express3 seems to have cookie session support built in though.  So when/if I upgrade to the that, I might stop using this.
